project:
  type: website
  output-dir: docs

website:
  title: "WetFlorVegChange"

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."

  sidebar:
    pinned: true
    align: center
    style: "docked"
    search: true
    logo: logo_screenshot.png
    logo-height: 50px
    logo-alt: "Logo"
    collapse-level: 2
    contents:
      - text: "About the project"
        file: index.qmd

      - section: "People and cooperations"
        file: People/people_cooperations.qmd
        contents:
          - text: "Core team"
            file: People/core_team.qmd
          - text: "Data contributors"
            file: People/data_contributors.qmd

      - section: "More about the project"
        file: More/more_about.qmd
        contents:
          - text: "Data requirements"
            file: More/What_data.qmd      
          - text: "How to contribute"
            file: More/instructions.qmd
          - text: "Data policy"
            file: More/data_policy.qmd

      - section: "Articles"
        file: Articles/articles.qmd
        contents:
          - text: "Project articles"
            file: Articles/project_articles.qmd
          - text: "Related articles"
            file: Articles/related_articles.qmd
            
      - text: "Links"
        file: Links.qmd

format:
  html:
    theme: cosmo
    toc: true
