---
format: html
editor: visual
---

# Interesting publications about the topic

Alfonsi, E., Benot, M. L., Fievet, V., & Alard, D. (2017). Addressing species turnover and community changes in vegetation resurvey studies. *Applied Vegetation Science*, *20*(2), 172-182. [Doi: 10.1111/avsc.12258](https://doi.org/10.1111/avsc.12258)

Bergamini, A., Peintinger, M., Fakheran, S., Moradi, H., Schmid, B., & Joshi, J. (2009). Loss of habitat specialists despite conservation management in fen remnants 1995–2006. Perspectives in Plant Ecology, Evolution and Systematics, 11(1), 65-79. [Doi: 10.1016/j.ppees.2008.10.001](https://doi.org/10.1016/j.ppees.2008.10.001)

Britton, A. J., Hewison, R. L., Mitchell, R. J., & Riach, D. (2017). Pollution and climate change drive long-term change in Scottish wetland vegetation composition. *Biological Conservation*, *210*, 72-79. https://doi.org/10.1034/j.1600-0587.2002.250605.x

Burnside, N. G., Joyce, C. B., Puurmann, E., & Scott, D. M. (2007). Use of vegetation classification and plant indicators to assess grazing abandonment in Estonian coastal wetlands. *Journal of Vegetation Science*, *18*(5), 645-654. [Doi: 10.1111/j.1654-1103.2007.tb02578.x](https://doi.org/10.1111/j.1654-1103.2007.tb02578.x)

Gunnarsson, U., Malmer, N., & Rydin, H. (2002). Dynamics or constancy in Sphagnum dominated mire ecosystems? A 40‐year study. Ecography, 25(6), 685-704. [Doi: 10.1034/j.1600-0587.2002.250605.x](https://doi.org/10.1034/j.1600-0587.2002.250605.x)

Hédl, R., Bernhardt-Römermann, M., Grytnes, J. A., Jurasinski, G., & Ewald, J. (2017). Resurvey of historical vegetation plots: a tool for understanding long-term dynamics of plant communities. *Applied Vegetation Science*, *20*(2), 161-163. [Doi: 10.1111/avsc.12307](https://www.jstor.org/stable/44211483)

Kapfer, J., Hédl, R., Jurasinski, G., Kopecký, M., Schei, F. H., & Grytnes, J. A. (2017). Resurveying historical vegetation data–opportunities and challenges. *Applied Vegetation Science*, *20*(2), 164-171. [Doi:10.1111/avsc.12269](https://doi.org/10.1111/avsc.12269)

Klinkovská, K., Glaser, M., Danihelka, J., Kaplan, Z., Knollová, I., Novotný, P., ... & Chytrý, M. (2024). Dynamics of the Czech flora over the last 60 years: Winners, losers and causes of changes. *Biological Conservation*, *292*, 110502. [Doi:10.1016/j.biocon.2024.110502](https://doi.org/10.1016/j.biocon.2024.110502)

Klinkovská, K., Sperandii, M. G., Knollová, I., Danihelka, J., Hájek, M., Hájková, P., ... & Chytrý, M. (2025). Half a Century of Temperate Non‐Forest Vegetation Changes: No Net Loss in Species Richness, but Considerable Shifts in Taxonomic and Functional Composition. *Global Change Biology*, *31*(1), e70030. [Doi:10.1111/gcb.70030](https://doi.org/10.1111/gcb.70030)

Knollová, I., Chytrý, M., Bruelheide, H., Dullinger, S., Jandt, U., Bernhardt‐Römermann, M., ... & Moiseev, P. (2024). ReSurveyEurope: A database of resurveyed vegetation plots in Europe. *Journal of Vegetation Science*, *35*(2), e13235. [Doi: 10.1111/jvs.13235](https://doi.org/10.1111/jvs.13235)

Jandt, U., Bruelheide, H., Berg, C., Bernhardt-Römermann, M., Blüml, V., Bode, F., ... & Wulf, M. (2022). ReSurveyGermany: Vegetation-plot time-series over the past hundred years in Germany. *Scientific Data*, *9*(1), 631. [Doi: 10.1038/s41597-022-01688-6](https://doi.org/10.1038/s41597-022-01688-6)

Midolo, G., Clark, A. T., Chytrý, M., Essl, F., Dullinger, S., Jandt, U., ... & Keil, P. (2026). Sixty years of plant community change in Europe indicate a shift toward nutrient-richer and denser vegetation. *Science Advances*, *12*(15), eaeb2493. [Doi: 10.1126/sciadv.aeb2493](https://www.science.org/doi/full/10.1126/sciadv.aeb2493)

Ortmann-Ajkai, A., Csicsek, G., Hollós, R., Magyaros, V., Wágner, L., & Lóczy, D. (2018). Twenty-years’ changes of wetland vegetation: effects of floodplain-level threats. *Wetlands*, *38*(3), 591-604. [Doi: 10.1007/s13157-018-1002-0](https://doi.org/10.1007/s13157-018-1002-0)

Pinceloup, N., Poulin, M., Brice, M. H., & Pellerin, S. (2020). Vegetation changes in temperate ombrotrophic peatlands over a 35 year period. *PLoS One*, *15*(2), e0229146. [Doi: 10.1371/journal.pone.0229146](https://doi.org/10.1371/journal.pone.0229146)

Rion, V., Gallandat, J. D., Gobat, J. M., & Vittoz, P. (2018). Recent changes in the plant composition of wetlands in the Jura Mountains. *Applied Vegetation Science*, *21*(1), 121-131. [DOI: 10.1111/avsc.12338](https://doi.org/10.1111/avsc.12338)

Sopotlieva, D., Velev, N., Terziyska, T., & Apostolova, I. (2024, December). Mountain Wetland Vegetation Changes for Thirteen Years in Vitosha Mountain (Bulgaria). In *Proceedings of the Bulgarian Academy of Sciences* (Vol. 77, No. 12, pp. 1776-1783). [Doi: 10.7546/CRABS.2024.12.05](https://doi.org/10.7546/CRABS.2024.12.05)

ter Braak, C. J., & Wiertz, J. (1994). On the statistical analysis of vegetation change: a wetland affected by water extraction and soil acidification. *Journal of Vegetation Science*, 5(3), 361-372. [Doi: 10.2307/3235860](https://doi.org/10.2307/3235860)
